### ISSUE TITLE
msixbundle install Abort Error

### ISSUE THREAD

**Issue by sergeivich** [MadCkull/WSAppBak#2]
Unable to install with double click due to unverified certificates
Unable to install with powershell in admin:

Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but terminated in a root
certificate which is not trusted by the trust provider.
error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
NOTE: For additional information, look for [ActivityId] 1177c2d5-ebd8-0006-8971-a611d8ebda01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 1177c2d5-ebd8-0006-8971-a611d8ebda01

**Comment by MadCkull** [comment]
Before Installing Package, Please ensure you've installed the certificate. Here's how:
1. Go to **Properties**.
2. In the "Digital Signature" tab, select the signature and click **Details**.
3. Click **View Certificates**, then **Install Certificate**. Select **Local Machine** and choose **Browse** > **Trusted People** as the store location.
4. Install it

Now you're ready to install the package! If you need any assistance, feel free to reach out.

**Comment by sergeivich** [comment]
Worked out beautifully.
