### ISSUE TITLE
Error when installing your app

### ISSUE THREAD

**Issue by kunsh13** [MadCkull/WSAppBak#3]
Error shown when installing your WSAppBak msixbundle file

![image](https://github.com/user-attachments/assets/1ab3c6cb-9a56-418a-b58d-98a71a47c720)

**Comment by MadCkull** [comment]
You need to install certificate before installing the package. Here's how:

Go to **Properties**.
In the "**Digital Signature**" tab, select the **signature** and click **Details**.
Click **View Certificates**, then Install Certificate. Select **Local Machine** and choose Browse > **Trusted People** as the store location.
Install it
Now you're ready to install the package! If you need any assistance, feel free to reach out.

**Comment by kunsh13** [comment]
> You need to install certificate before installing the package. Here's how:
> 
> Go to **Properties**. In the "**Digital Signature**" tab, select the **signature** and click **Details**. Click **View Certificates**, then Install Certificate. Select **Local Machine** and choose Browse > **Trusted People** as the store location. Install it Now you're ready to install the package! If you need any assistance, feel free to reach out.

Thank you🤗

**Comment by CyberOfDemon** [comment]
<img width="405" height="509" alt="Image" src="https://github.com/user-attachments/assets/34e2e39b-bd58-4896-a5e3-196e795d76e3" />
How to fix this ?

**Comment by MadCkull** [comment]
Hii, Certificate is currently expired (I'll get a new one eventually, keep your shirt on). Until then, you have two choices:

- Download the source code and compile it yourself.
- Set your system clock back to early 2024 or maybe 2023 (I forgot 🙄), install it into **Trusted People**.

And the **Details** button is greyed out, try actually clicking the certificate name first. It’s not broken.. it’s just waiting for you to notice it. 🙂

**Comment by CyberOfDemon** [comment]
Hi, I have no idea about any Github subject and work. I was just looking for some solution for Microsoft Store app cracker and I found your tool so just answer me kindly, Is this app can be crack ? "https://apps.microsoft.com/detail/9NQ8150P1X4X?hl=en-us&gl=BD&ocid=pdpshare"
I will very thankful to you if you can help me to get the crack version of it. 👏
